bcp TaskStore.dbo.Actions OUT Actions.dat -f Actions.xml -U ogazitt@t1z9p4huyg -P zrc022.. -S t1z9p4huyg.database.windows.net
bcp TaskStore.dbo.aspnet_Applications OUT aspnet_Applications.dat -f aspnet_Applications.xml -U ogazitt@t1z9p4huyg -P zrc022.. -S t1z9p4huyg.database.windows.net
bcp TaskStore.dbo.aspnet_Membership OUT aspnet_Membership.dat -f aspnet_Membership.xml -U ogazitt@t1z9p4huyg -P zrc022.. -S t1z9p4huyg.database.windows.net
bcp TaskStore.dbo.aspnet_SchemaVersions OUT aspnet_SchemaVersions.dat -f aspnet_SchemaVersions.xml -U ogazitt@t1z9p4huyg -P zrc022.. -S t1z9p4huyg.database.windows.net
bcp TaskStore.dbo.aspnet_Users OUT aspnet_Users.dat -f aspnet_Users.xml -U ogazitt@t1z9p4huyg -P zrc022.. -S t1z9p4huyg.database.windows.net
bcp TaskStore.dbo.Colors OUT Colors.dat -f Colors.xml -U ogazitt@t1z9p4huyg -P zrc022.. -S t1z9p4huyg.database.windows.net
bcp TaskStore.dbo.Fields OUT Fields.dat -f Fields.xml -U ogazitt@t1z9p4huyg -P zrc022.. -S t1z9p4huyg.database.windows.net
bcp TaskStore.dbo.FieldTypes OUT FieldTypes.dat -f FieldTypes.xml -U ogazitt@t1z9p4huyg -P zrc022.. -S t1z9p4huyg.database.windows.net
bcp TaskStore.dbo.ListTypes OUT ListTypes.dat -f ListTypes.xml -U ogazitt@t1z9p4huyg -P zrc022.. -S t1z9p4huyg.database.windows.net
bcp TaskStore.dbo.Priorities OUT Priorities.dat -f Priorities.xml -U ogazitt@t1z9p4huyg -P zrc022.. -S t1z9p4huyg.database.windows.net
bcp TaskStore.dbo.Tags OUT Tags.dat -f Tags.xml -U ogazitt@t1z9p4huyg -P zrc022.. -S t1z9p4huyg.database.windows.net
bcp TaskStore.dbo.TaskLists OUT TaskLists.dat -f TaskLists.xml -U ogazitt@t1z9p4huyg -P zrc022.. -S t1z9p4huyg.database.windows.net
bcp TaskStore.dbo.Tasks OUT Tasks.dat -f Tasks.xml -U ogazitt@t1z9p4huyg -P zrc022.. -S t1z9p4huyg.database.windows.net
bcp TaskStore.dbo.TaskTags OUT TaskTags.dat -f TaskTags.xml -U ogazitt@t1z9p4huyg -P zrc022.. -S t1z9p4huyg.database.windows.net
bcp TaskStore.dbo.Users OUT Users.dat -f Users.xml -U ogazitt@t1z9p4huyg -P zrc022.. -S t1z9p4huyg.database.windows.net
